// resources/js/Components/PitchWriter/ChatComposer.jsx
import { useRef } from 'react';

export default function ChatComposer({ isBusy, onSend, onStop, disabled = false }) {
    const inputRef = useRef(null);

    const handleSubmit = (event) => {
        event.preventDefault();

        const content = inputRef.current?.value ?? '';

        if (!content.trim() || isBusy || disabled) {
            return;
        }

        onSend(content);

        if (inputRef.current) {
            inputRef.current.value = '';
        }
    };

    return (
        <form className="chat-compose" onSubmit={handleSubmit}>
            <label className="sr-only" htmlFor="writer-input">
                Сообщение AI
            </label>
            <input
                ref={inputRef}
                className="input"
                id="writer-input"
                type="text"
                placeholder="Ответьте AI или попросите переписать блок…"
                autoComplete="off"
                disabled={disabled || isBusy}
            />
            {isBusy ? (
                <button type="button" className="btn btn-secondary" onClick={onStop}>
                    Стоп
                </button>
            ) : (
                <button type="submit" className="btn btn-primary" disabled={disabled}>
                    Отправить
                </button>
            )}
        </form>
    );
}

// resources/js/Components/PitchWriter/ChatComposer.vue
<script setup lang="ts">
import { ref } from 'vue';

const props = withDefaults(defineProps<{
    isBusy?: boolean;
    onSend?: (content: string) => void;
    onStop?: () => void;
    disabled?: boolean;
}>(), {
    isBusy: false,
    disabled: false,
});

const inputRef = ref<HTMLInputElement | null>(null);

const handleSubmit = (event: Event) => {
    event.preventDefault();

    const content = inputRef.value?.value ?? '';

    if (!content.trim() || props.isBusy || props.disabled) {
        return;
    }

    props.onSend?.(content);

    if (inputRef.value) {
        inputRef.value.value = '';
    }
};
</script>

<template>
    <form class="chat-compose" @submit="handleSubmit">
        <label class="sr-only" for="writer-input">Сообщение AI</label>
        <input
            ref="inputRef"
            class="input"
            id="writer-input"
            type="text"
            placeholder="Ответьте AI или попросите переписать блок…"
            autocomplete="off"
            :disabled="disabled || isBusy"
        />
        <button v-if="isBusy" type="button" class="btn btn-secondary" @click="onStop">
            Стоп
        </button>
        <button v-else type="submit" class="btn btn-primary" :disabled="disabled">
            Отправить
        </button>
    </form>
</template>
