// resources/js/Components/PitchRecorder/ErrorBanner.vue
<script setup lang="ts">
import { AlertCircle } from 'lucide-vue-next';

withDefaults(defineProps<{ errors?: string[]; variant?: 'card' | 'video' }>(), {
    errors: () => [],
    variant: 'card',
});
</script>

<template>
    <Transition name="banner">
        <div
            v-if="errors.length"
            class="p-3 rounded-xl text-sm flex items-start gap-2"
            :class="variant === 'video'
                ? 'absolute top-20 left-1/2 -translate-x-1/2 w-auto max-w-sm z-30 shadow-lg'
                : 'm-4'"
            :style="variant === 'video'
                ? { backgroundColor: 'rgba(239,68,68,0.9)', backdropFilter: 'blur(8px)', color: 'white' }
                : { backgroundColor: 'var(--danger-subtle)', color: 'var(--danger)', border: '1px solid rgba(239,68,68,0.2)' }"
        >
            <AlertCircle class="w-4 h-4 shrink-0 mt-0.5" :stroke-width="1.5" />
            <div>
                <p v-for="(error, index) in errors" :key="index">{{ error }}</p>
            </div>
        </div>
    </Transition>
</template>

<style scoped>
.banner-enter-active,
.banner-leave-active {
    transition: opacity 0.25s ease, transform 0.25s ease;
}

.banner-enter-from,
.banner-leave-to {
    opacity: 0;
    transform: translateY(-8px);
}
</style>

// resources/js/Components/PitchRecorder/ErrorBanner.jsx
import { motion, AnimatePresence } from 'framer-motion';
import { AlertCircle } from 'lucide-react';

export default function ErrorBanner({ errors = [], variant = 'card' }) {
    if (errors.length === 0) {
        return null;
    }

    const isVideo = variant === 'video';

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0, y: isVideo ? 8 : -8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: isVideo ? 8 : -8 }}
                className={isVideo
                    ? 'absolute top-20 left-4 right-4 p-3 rounded-xl text-sm z-30 flex items-start gap-2'
                    : 'm-4 p-3 rounded-xl text-sm flex items-start gap-2'}
                style={isVideo
                    ? { backgroundColor: 'rgba(239,68,68,0.9)', backdropFilter: 'blur(8px)', color: 'white' }
                    : { backgroundColor: 'var(--danger-subtle)', color: 'var(--danger)', border: '1px solid rgba(239,68,68,0.2)' }}
            >
                <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" strokeWidth={1.5} />
                <div>
                    {errors.map((error, index) => (
                        <p key={index}>{error}</p>
                    ))}
                </div>
            </motion.div>
        </AnimatePresence>
    );
}
