// resources/js/Components/PitchRecorder/index.jsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useForm } from '@inertiajs/react';
import { route } from 'ziggy-js';
import { useMediaDevices } from '@/hooks/useMediaDevices';
import { usePitchRecorder } from '@/hooks/usePitchRecorder';
import AudioRecorderView from './AudioRecorderView';
import ProcessingOverlay from './ProcessingOverlay';
import VideoRecorderView from './VideoRecorderView';

const MAX_DURATION_SECONDS = 600;

export default function PitchRecorder({
    defaultDuration,
    mode: selectedMode,
    onRecordingStateChange,
    layout = 'fullscreen',
    onStudioStateChange,
    onRequestAudioFallback,
}) {
    const [targetTimeMins, setTargetTimeMins] = useState(Math.round(defaultDuration / 60) || 3);
    const mode = selectedMode === 'audio' || selectedMode === 'video' ? selectedMode : null;

    const {
        initState: devicesInitState,
        error: devicesError,
        devices,
        selectedAudioId,
        selectedVideoId,
        setSelectedAudioId,
        setSelectedVideoId,
        cameraUnavailable,
        rediscover,
    } = useMediaDevices({
        mode,
        enabled: Boolean(mode),
    });

    const devicesReady = devicesInitState === 'ready';

    const recorder = usePitchRecorder({
        mode: mode ?? 'audio',
        audioDeviceId: selectedAudioId,
        videoDeviceId: selectedVideoId,
        maxDurationSeconds: MAX_DURATION_SECONDS,
        enabled: Boolean(mode) && devicesReady,
    });

    const { setData, post, progress, processing, errors } = useForm({
        video: null,
        duration: targetTimeMins * 60,
        media_type: mode ?? 'video',
    });

    useEffect(() => {
        setData('duration', targetTimeMins * 60);
    }, [setData, targetTimeMins]);

    useEffect(() => {
        if (mode) {
            setData('media_type', mode);
        }
    }, [mode, setData]);

    useEffect(() => {
        if (onRecordingStateChange) {
            onRecordingStateChange(recorder.isRecording);
        }
    }, [onRecordingStateChange, recorder.isRecording]);

    const initState = useMemo(() => {
        if (!mode || devicesInitState === 'idle') {
            return 'idle';
        }

        if (devicesInitState === 'loading' || (devicesReady && recorder.initState === 'loading')) {
            return 'loading';
        }

        if (devicesInitState === 'error' || recorder.initState === 'error') {
            return 'error';
        }

        return 'ready';
    }, [devicesInitState, devicesReady, mode, recorder.initState]);

    const initError = devicesError ?? (recorder.initState === 'error' ? recorder.error : null);

    const handleStop = useCallback(async () => {
        const result = await recorder.stopRecording();

        if (result?.file) {
            setData('video', result.file);
            setData('media_type', result.mediaType);
        }
    }, [recorder.stopRecording, setData]);

    const handleReset = useCallback(async () => {
        setData('video', null);
        await recorder.resetRecording();
    }, [recorder.resetRecording, setData]);

    const submitPitch = useCallback(() => {
        if (!recorder.recordedFile) {
            return;
        }

        post(route('pitch.upload'));
    }, [post, recorder.recordedFile]);

    const sharedProps = useMemo(() => ({
        initState,
        initError,
        isRecording: recorder.isRecording,
        isPaused: recorder.isPaused,
        isRecorded: recorder.isRecorded,
        recordingTime: recorder.recordingTime,
        maxDurationSeconds: MAX_DURATION_SECONDS,
        targetTimeMins,
        onTargetTimeChange: setTargetTimeMins,
        recordedUrl: recorder.recordedUrl,
        recordedFile: recorder.recordedFile,
        nativeMediaRecorder: recorder.nativeMediaRecorder,
        previewStream: recorder.previewStream,
        formErrors: errors,
        recorderError: recorder.error,
        devices,
        selectedAudioId,
        selectedVideoId,
        onAudioDeviceChange: setSelectedAudioId,
        onVideoDeviceChange: setSelectedVideoId,
        onStart: recorder.startRecording,
        onPause: recorder.pauseRecording,
        onResume: recorder.resumeRecording,
        onStop: handleStop,
        onReset: handleReset,
        onSubmit: submitPitch,
        cameraUnavailable,
        layout,
        mode,
        processing,
        progress,
        previewVideoRef: recorder.previewVideoRef,
        reattachPreview: recorder.reattachPreview,
        rediscover,
        onRequestAudioFallback,
    }), [
        initState,
        initError,
        recorder.isRecording,
        recorder.isPaused,
        recorder.isRecorded,
        recorder.recordingTime,
        targetTimeMins,
        recorder.recordedUrl,
        recorder.recordedFile,
        recorder.nativeMediaRecorder,
        recorder.previewStream,
        errors,
        recorder.error,
        devices,
        selectedAudioId,
        selectedVideoId,
        recorder.startRecording,
        recorder.pauseRecording,
        recorder.resumeRecording,
        recorder.reattachPreview,
        cameraUnavailable,
        layout,
        mode,
        processing,
        progress,
        recorder.previewVideoRef,
        handleStop,
        handleReset,
        submitPitch,
        rediscover,
        onRequestAudioFallback,
    ]);

    useEffect(() => {
        if (layout !== 'studio' || !onStudioStateChange) {
            return;
        }

        onStudioStateChange(sharedProps);
    }, [layout, onStudioStateChange, sharedProps]);

    if (processing) {
        if (layout === 'studio') {
            return null;
        }

        return <ProcessingOverlay progress={progress} />;
    }

    if (layout === 'studio') {
        return null;
    }

    if (!mode) {
        return null;
    }

    if (mode === 'audio') {
        return <AudioRecorderView {...sharedProps} />;
    }

    return (
        <VideoRecorderView
            {...sharedProps}
            previewVideoRef={recorder.previewVideoRef}
        />
    );
}

// resources/js/Components/PitchRecorder/index.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useForm } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import { useMediaDevices } from '@/composables/useMediaDevices';
import { usePitchRecorder } from '@/composables/usePitchRecorder';
import type { MediaMode } from '@/lib/media/mediaConstraints';
import AudioRecorderView from './AudioRecorderView.vue';
import ProcessingOverlay from './ProcessingOverlay.vue';
import VideoRecorderView from './VideoRecorderView.vue';

const MAX_DURATION_SECONDS = 600;

const props = withDefaults(defineProps<{
    defaultDuration?: number;
    mode?: string | null;
    onRecordingStateChange?: (recording: boolean) => void;
    layout?: 'fullscreen' | 'studio';
    onStudioStateChange?: (state: any) => void;
    onRequestAudioFallback?: () => void;
}>(), {
    defaultDuration: 180,
    mode: null,
    layout: 'fullscreen',
});

const targetTimeMins = ref(Math.round(props.defaultDuration / 60) || 3);
const setTargetTimeMins = (mins: number) => {
    targetTimeMins.value = mins;
};

const resolvedMode = computed<MediaMode | null>(() =>
    props.mode === 'audio' || props.mode === 'video' ? (props.mode as MediaMode) : null,
);

const mediaDevices = useMediaDevices({
    mode: resolvedMode,
    enabled: () => Boolean(resolvedMode.value),
});

const devicesReady = computed(() => mediaDevices.initState === 'ready');

const recorder = usePitchRecorder({
    mode: () => resolvedMode.value ?? 'audio',
    audioDeviceId: () => mediaDevices.selectedAudioId,
    videoDeviceId: () => mediaDevices.selectedVideoId,
    maxDurationSeconds: MAX_DURATION_SECONDS,
    enabled: () => Boolean(resolvedMode.value) && mediaDevices.initState === 'ready',
});

const form = useForm<{ video: File | null; duration: number; media_type: string }>({
    video: null,
    duration: targetTimeMins.value * 60,
    media_type: resolvedMode.value ?? 'video',
});

watch(targetTimeMins, (mins) => {
    form.duration = mins * 60;
});
watch(resolvedMode, (mode) => {
    if (mode) {
        form.media_type = mode;
    }
});
watch(() => recorder.isRecording.value, (recording) => props.onRecordingStateChange?.(recording));

const initState = computed<string>(() => {
    if (!resolvedMode.value || mediaDevices.initState === 'idle') {
        return 'idle';
    }

    if (mediaDevices.initState === 'loading' || (devicesReady.value && recorder.initState.value === 'loading')) {
        return 'loading';
    }

    if (mediaDevices.initState === 'error' || recorder.initState.value === 'error') {
        return 'error';
    }

    return 'ready';
});

const initError = computed(() =>
    mediaDevices.error ?? (recorder.initState.value === 'error' ? recorder.error.value : null));

const handleStop = async () => {
    const result = await recorder.stopRecording();

    if (result?.file) {
        form.video = result.file;
        form.media_type = result.mediaType;
    }
};

const handleReset = async () => {
    form.video = null;
    await recorder.resetRecording();
};

const submitPitch = () => {
    if (!recorder.recordedFile.value) {
        return;
    }

    form.post(route('pitch.upload'));
};

const sharedProps = computed(() => ({
    initState: initState.value,
    initError: initError.value,
    isRecording: recorder.isRecording.value,
    isPaused: recorder.isPaused.value,
    isRecorded: recorder.isRecorded.value,
    recordingTime: recorder.recordingTime.value,
    maxDurationSeconds: MAX_DURATION_SECONDS,
    targetTimeMins: targetTimeMins.value,
    onTargetTimeChange: setTargetTimeMins,
    recordedUrl: recorder.recordedUrl.value,
    recordedFile: recorder.recordedFile.value,
    nativeMediaRecorder: recorder.nativeMediaRecorder.value,
    previewStream: recorder.previewStream.value,
    formErrors: form.errors,
    recorderError: recorder.error.value,
    devices: mediaDevices.devices,
    selectedAudioId: mediaDevices.selectedAudioId,
    selectedVideoId: mediaDevices.selectedVideoId,
    onAudioDeviceChange: mediaDevices.setSelectedAudioId,
    onVideoDeviceChange: mediaDevices.setSelectedVideoId,
    onStart: recorder.startRecording,
    onPause: recorder.pauseRecording,
    onResume: recorder.resumeRecording,
    onStop: handleStop,
    onReset: handleReset,
    onSubmit: submitPitch,
    layout: props.layout,
    mode: resolvedMode.value,
    processing: form.processing,
    progress: form.progress,
    previewVideoRef: recorder.previewVideoRef,
    reattachPreview: recorder.reattachPreview,
    rediscover: mediaDevices.rediscover,
    onRequestAudioFallback: props.onRequestAudioFallback,
}));

watch(sharedProps, (state) => {
    if (props.layout === 'studio') {
        props.onStudioStateChange?.(state);
    }
});
</script>

<template>
    <template v-if="layout !== 'studio'">
        <ProcessingOverlay v-if="form.processing" :progress="form.progress" />
        <AudioRecorderView v-else-if="resolvedMode === 'audio'" v-bind="sharedProps" />
        <VideoRecorderView v-else-if="resolvedMode === 'video'" v-bind="sharedProps" />
    </template>
</template>
