// resources/js/Layouts/AppLayout.jsx
import { Link, usePage } from '@inertiajs/react';
import { route } from 'ziggy-js';
import { Mic, Clock, LogOut, Bot } from 'lucide-react';
import ThemeToggle from '@/Components/ThemeToggle';
import LogoMark from '@/Components/LogoMark';

const navItems = [
    {
        href: () => route('pitch.index'),
        label: 'Новая запись',
        shortLabel: 'Запись',
        icon: Mic,
        isActive: (pathname, search) =>
            !search.includes('tab=history') && pathname === new URL(route('pitch.index'), window.location).pathname,
    },
    {
        href: () => `${route('pitch.index')}?tab=history`,
        label: 'История',
        shortLabel: 'История',
        icon: Clock,
        isActive: (pathname, search) => search.includes('tab=history'),
    },
    {
        href: () => route('pitch-writer.index'),
        label: 'Питч Райтер',
        shortLabel: 'Райтер',
        icon: Bot,
        isActive: (pathname) => pathname === new URL(route('pitch-writer.index'), window.location).pathname,
    },
];

function NavItem({ item }) {
    const isActive = item.isActive(window.location.pathname, window.location.search);

    return (
        <Link href={item.href()} className={`nav-item${isActive ? ' active' : ''}`}>
            <item.icon strokeWidth={1.5} aria-hidden="true" />
            {item.label}
        </Link>
    );
}

function AttemptsDisplay({ used, max }) {
    const percentage = max > 0 ? (used / max) * 100 : 0;

    return (
        <div className="attempts-bar">
            <div className="attempts-bar-top">
                <span>Попытки</span>
                <span className="mono">{used}/{max}</span>
            </div>
            <div className="attempts-track">
                <div className="attempts-fill" style={{ width: `${Math.min(percentage, 100)}%` }} />
            </div>
        </div>
    );
}

export default function AppLayout({ children, chrome = true }) {
    const { auth_email, attempts_used, max_attempts, status, errors } = usePage().props;
    const avatarLetter = auth_email ? auth_email.charAt(0).toUpperCase() : 'U';

    if (!chrome) {
        return (
            <div className="app-shell app-shell--chrome-off">
                <div className="main-col">
                    <div className="main-content">{children}</div>
                </div>
            </div>
        );
    }

    return (
        <div className="app-shell">
            <aside className="sidebar">
                <Link href={route('pitch.index')} className="sidebar-logo">
                    <LogoMark size={28} />
                    <span>Pitch AI</span>
                </Link>

                <nav className="sidebar-nav">
                    {navItems.map((item) => (
                        <NavItem key={item.label} item={item} />
                    ))}
                </nav>

                <div className="sidebar-footer">
                    <AttemptsDisplay used={attempts_used} max={max_attempts} />

                    <div className="user-row">
                        <div className="user-avatar">{avatarLetter}</div>
                        <span className="user-email">{auth_email}</span>
                        <Link
                            href={route('auth.logout')}
                            method="post"
                            as="button"
                            className="btn-icon"
                            title="Выйти"
                            aria-label="Выйти"
                        >
                            <LogOut strokeWidth={1.5} />
                        </Link>
                    </div>
                </div>
            </aside>

            <div className="main-col">
                <header className="app-header">
                    <Link href={route('pitch.index')} className="app-brand">
                        <LogoMark size={24} />
                        <strong>Pitch AI</strong>
                    </Link>
                    <div className="flex items-center gap-3 ml-auto">
                        <span className="md:hidden text-xs mono" style={{ color: 'var(--muted)' }}>
                            {attempts_used}/{max_attempts}
                        </span>
                        <ThemeToggle />
                    </div>
                </header>

                <main className="main-content">
                    {status && (
                        <div
                            className="mx-4 md:mx-6 mt-4 px-4 py-3 rounded-xl text-sm"
                            style={{
                                backgroundColor: 'var(--success-subtle)',
                                color: 'var(--success)',
                                border: '1px solid color-mix(in oklch, var(--success) 30%, transparent)',
                            }}
                        >
                            {status === 'code-sent' ? 'Код успешно отправлен!' : status}
                        </div>
                    )}

                    {Object.keys(errors || {}).length > 0 && (
                        <div
                            className="mx-4 md:mx-6 mt-4 px-4 py-3 rounded-xl text-sm"
                            style={{
                                backgroundColor: 'var(--danger-subtle)',
                                color: 'var(--danger)',
                                border: '1px solid color-mix(in oklch, var(--danger) 30%, transparent)',
                            }}
                        >
                            <p className="font-medium mb-1">Ошибки:</p>
                            <ul className="space-y-0.5">
                                {Object.values(errors).map((error, idx) => (
                                    <li key={idx}>• {error}</li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {children}
                </main>

                <nav className="bottom-nav">
                    {navItems.map((item) => {
                        const isActive = item.isActive(window.location.pathname, window.location.search);

                        return (
                            <Link
                                key={item.label}
                                href={item.href()}
                                className={isActive ? 'active' : undefined}
                            >
                                <item.icon strokeWidth={1.5} aria-hidden="true" />
                                {item.shortLabel}
                            </Link>
                        );
                    })}
                </nav>
            </div>
        </div>
    );
}

// resources/js/Layouts/AppLayout.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Link, usePage } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import { Bot, Clock, LogOut, Mic } from 'lucide-vue-next';
import ThemeToggle from '@/Components/ThemeToggle.vue';
import LogoMark from '@/Components/LogoMark.vue';

withDefaults(defineProps<{ chrome?: boolean }>(), { chrome: true });

const page = usePage<{
    auth_email: string | null;
    attempts_used: number;
    max_attempts: number;
    status: string | null;
    errors: Record<string, string>;
}>();

const pitchPath = new URL(route('pitch.index')).pathname;
const writerPath = new URL(route('pitch-writer.index')).pathname;

const pathname = computed(() => page.url.split('?')[0]);

const navItems = [
    { href: () => route('pitch.index'), label: 'Новая запись', shortLabel: 'Запись', icon: Mic, kind: 'new' as const },
    { href: () => `${route('pitch.index')}?tab=history`, label: 'История', shortLabel: 'История', icon: Clock, kind: 'history' as const },
    { href: () => route('pitch-writer.index'), label: 'Питч Райтер', shortLabel: 'Райтер', icon: Bot, kind: 'writer' as const },
];

const isActive = (kind: 'new' | 'history' | 'writer'): boolean => {
    if (kind === 'history') {
        return page.url.includes('tab=history');
    }

    if (kind === 'writer') {
        return pathname.value === writerPath;
    }

    return !page.url.includes('tab=history') && pathname.value === pitchPath;
};

const avatarLetter = computed(() =>
    page.props.auth_email ? page.props.auth_email.charAt(0).toUpperCase() : 'U',
);

const attemptsPercentage = computed(() =>
    page.props.max_attempts > 0 ? (page.props.attempts_used / page.props.max_attempts) * 100 : 0,
);

const errorValues = computed(() => Object.values(page.props.errors ?? {}));
</script>

<template>
    <div v-if="!chrome" class="app-shell app-shell--chrome-off">
        <div class="main-col">
            <div class="main-content"><slot /></div>
        </div>
    </div>

    <div v-else class="app-shell">
        <aside class="sidebar">
            <Link :href="route('pitch.index')" class="sidebar-logo">
                <LogoMark :size="28" />
                <span>Pitch AI</span>
            </Link>

            <nav class="sidebar-nav">
                <Link
                    v-for="item in navItems"
                    :key="item.label"
                    :href="item.href()"
                    class="nav-item"
                    :class="{ active: isActive(item.kind) }"
                >
                    <component :is="item.icon" :stroke-width="1.5" aria-hidden="true" />
                    {{ item.label }}
                </Link>
            </nav>

            <div class="sidebar-footer">
                <div class="attempts-bar">
                    <div class="attempts-bar-top">
                        <span>Попытки</span>
                        <span class="mono">{{ page.props.attempts_used }}/{{ page.props.max_attempts }}</span>
                    </div>
                    <div class="attempts-track">
                        <div class="attempts-fill" :style="{ width: `${Math.min(attemptsPercentage, 100)}%` }" />
                    </div>
                </div>

                <div class="user-row">
                    <div class="user-avatar">{{ avatarLetter }}</div>
                    <span class="user-email">{{ page.props.auth_email }}</span>
                    <Link
                        :href="route('auth.logout')"
                        method="post"
                        as="button"
                        class="btn-icon"
                        title="Выйти"
                        aria-label="Выйти"
                    >
                        <LogOut :stroke-width="1.5" />
                    </Link>
                </div>
            </div>
        </aside>

        <div class="main-col">
            <header class="app-header">
                <Link :href="route('pitch.index')" class="app-brand">
                    <LogoMark :size="24" />
                    <strong>Pitch AI</strong>
                </Link>
                <div class="flex items-center gap-3 ml-auto">
                    <span class="md:hidden text-xs mono" :style="{ color: 'var(--muted)' }">
                        {{ page.props.attempts_used }}/{{ page.props.max_attempts }}
                    </span>
                    <ThemeToggle />
                </div>
            </header>

            <main class="main-content">
                <div
                    v-if="page.props.status"
                    class="mx-4 md:mx-6 mt-4 px-4 py-3 rounded-xl text-sm"
                    :style="{
                        backgroundColor: 'var(--success-subtle)',
                        color: 'var(--success)',
                        border: '1px solid color-mix(in oklch, var(--success) 30%, transparent)',
                    }"
                >
                    {{ page.props.status === 'code-sent' ? 'Код успешно отправлен!' : page.props.status }}
                </div>

                <div
                    v-if="errorValues.length > 0"
                    class="mx-4 md:mx-6 mt-4 px-4 py-3 rounded-xl text-sm"
                    :style="{
                        backgroundColor: 'var(--danger-subtle)',
                        color: 'var(--danger)',
                        border: '1px solid color-mix(in oklch, var(--danger) 30%, transparent)',
                    }"
                >
                    <p class="font-medium mb-1">Ошибки:</p>
                    <ul class="space-y-0.5">
                        <li v-for="(error, idx) in errorValues" :key="idx">• {{ error }}</li>
                    </ul>
                </div>

                <slot />
            </main>

            <nav class="bottom-nav">
                <Link
                    v-for="item in navItems"
                    :key="item.label"
                    :href="item.href()"
                    :class="{ active: isActive(item.kind) }"
                >
                    <component :is="item.icon" :stroke-width="1.5" aria-hidden="true" />
                    {{ item.shortLabel }}
                </Link>
            </nav>
        </div>
    </div>
</template>
